import fs from 'fs';
import path from 'path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * A CURATED sidebar, grouped by what the reader is trying to do.
 *
 * It used to be `{type: 'autogenerated'}`, which mirrored the folder tree: 16
 * top-level sections, all the same weight, ordered by `sidebar_position`
 * numbers rather than by any journey. Readers had to choose one of 16 before
 * knowing what any of them meant, and the site had no visible thread — the
 * complaint that prompted this change.
 *
 * The groups below are a path: start, learn the ideas, use the products, look
 * beyond Claude, apply it, go deep. Reference sits last because it is
 * consulted, not read.
 *
 * Two properties are deliberately preserved:
 *
 * 1. NO FILE MOVES. Grouping happens here, so every URL is unchanged and no
 *    inbound link or search result breaks.
 * 2. EACH SECTION KEEPS ITS OWN CATEGORY + INDEX PAGE, read from its existing
 *    `_category_.json`. A hand-written list would have dropped those index
 *    pages — the navbar links straight to them, so the build (fail-closed on
 *    broken links) caught it immediately. Reading the JSON instead of copying
 *    it keeps one source of truth: edit `_category_.json`, and the sidebar
 *    follows.
 *
 * Adding a page is still just adding a file: every section is an autogenerated
 * sub-tree.
 */

const DOCS = path.join(__dirname, 'docs');

/** The section's own category node, faithful to its `_category_.json`. */
function section(dirName: string) {
  const metaPath = path.join(DOCS, dirName, '_category_.json');
  const meta = fs.existsSync(metaPath)
    ? JSON.parse(fs.readFileSync(metaPath, 'utf8'))
    : {};
  return {
    type: 'category' as const,
    label: meta.label ?? dirName,
    collapsed: meta.collapsed ?? true,
    collapsible: meta.collapsible ?? true,
    // Keeps `/docs/<section>` alive — the navbar dropdown points at it.
    ...(meta.link ? {link: meta.link} : {}),
    items: [{type: 'autogenerated' as const, dirName}],
  };
}

/**
 * One macro-area wrapping several sections.
 *
 * When the area holds a SINGLE section, the wrapper is dropped and the section
 * is promoted, carrying the area's label. Otherwise the tree reads
 * "Start here › Start Here › page" — the same word twice, and an extra click
 * for nothing.
 */
const group = (label: string, dirs: string[], collapsed = true) => {
  if (dirs.length === 1) {
    return {...section(dirs[0]), label, collapsed};
  }
  return {
    type: 'category' as const,
    label,
    collapsed,
    items: dirs.map(section),
  };
};

const sidebars: SidebarsConfig = {
  docs: [
    // Open by default: a new reader should land on the on-ramp, not a wall of
    // closed folders.
    group('Start here', ['start-here'], false),

    // The transferable ideas — they make every tool below make sense.
    group('Learn the fundamentals', ['foundations', 'prompting']),

    // The products, ordered by how technical they get.
    group('Use Claude', ['claude-app', 'claude-code', 'api']),

    // Everything that is not Claude. Its own group because it is the largest
    // section on the site and was drowning the rest of the tree.
    group('Every other AI', ['models']),

    // Doing, rather than reading.
    group('Put it to work', ['playbooks', 'walkthroughs', 'templates', 'tools']),

    // Depth for people who already ship.
    group('Go deeper', ['power-user', 'security', 'frontiers']),

    // Consulted, not read — so it sits at the bottom.
    group('Reference', ['whats-new', 'contribute']),
  ],
};

export default sidebars;
