import React, {useMemo, useState, type ReactNode} from 'react';
import Link from '@docusaurus/Link';
import BrowserOnly from '@docusaurus/BrowserOnly';
import data from '@site/data/freshness.json';
import styles from './styles.module.css';

/**
 * FreshnessDashboard — a public, self-auditing ledger of every page's freshness.
 *
 * Data comes from data/freshness.json (generated by scripts/build-freshness.mjs).
 * Staleness is computed here, in the browser, against the reader's own "today",
 * so the dashboard itself can never go stale.
 */

type Page = {
  title: string;
  section: string;
  url: string;
  editUrl: string;
  lastVerified: string | null;
  source: string | null;
};

type Status = 'fresh' | 'aging' | 'stale' | 'unverified';

const FRESH_DAYS = 90;
const AGING_DAYS = 180;

/**
 * Status marks are rendered as tinted CSS discs, not emoji — the hue comes
 * from the same per-status class the cards and badges already use, so the
 * traffic-light reading survives without pasting coloured pictographs into
 * the markup. Colour is never the only channel: the visible label sits
 * directly beside every disc.
 */
const STATUS_META: Record<Status, {label: string}> = {
  fresh: {label: 'Fresh'},
  aging: {label: 'Aging'},
  stale: {label: 'Stale'},
  unverified: {label: 'Unverified'},
};

function daysSince(date: string): number {
  const then = new Date(date + 'T00:00:00Z').getTime();
  return Math.floor((Date.now() - then) / 86_400_000);
}

function statusOf(page: Page): Status {
  if (!page.lastVerified) return 'unverified';
  const d = daysSince(page.lastVerified);
  if (d <= FRESH_DAYS) return 'fresh';
  if (d <= AGING_DAYS) return 'aging';
  return 'stale';
}

function FreshnessDashboardInner(): ReactNode {
  const pages = data.pages as Page[];
  const sections = useMemo(
    () => ['all', ...Array.from(new Set(pages.map((p) => p.section))).sort()],
    [pages],
  );

  const [statusFilter, setStatusFilter] = useState<'all' | Status>('all');
  const [sectionFilter, setSectionFilter] = useState('all');
  const [sortBy, setSortBy] = useState<'age' | 'title' | 'section'>('age');

  const withStatus = useMemo(
    () => pages.map((p) => ({...p, status: statusOf(p)})),
    [pages],
  );

  const counts = useMemo(() => {
    const c: Record<Status, number> = {fresh: 0, aging: 0, stale: 0, unverified: 0};
    for (const p of withStatus) c[p.status]++;
    return c;
  }, [withStatus]);

  const rows = useMemo(() => {
    let r = withStatus.filter(
      (p) =>
        (statusFilter === 'all' || p.status === statusFilter) &&
        (sectionFilter === 'all' || p.section === sectionFilter),
    );
    const rank: Record<Status, number> = {stale: 0, aging: 1, unverified: 2, fresh: 3};
    r = [...r].sort((a, b) => {
      if (sortBy === 'title') return a.title.localeCompare(b.title);
      if (sortBy === 'section')
        return a.section.localeCompare(b.section) || a.title.localeCompare(b.title);
      // age: worst first (stale > aging > unverified > fresh), then oldest date
      if (rank[a.status] !== rank[b.status]) return rank[a.status] - rank[b.status];
      return (a.lastVerified ?? '').localeCompare(b.lastVerified ?? '');
    });
    return r;
  }, [withStatus, statusFilter, sectionFilter, sortBy]);

  const verifiedPct = Math.round((counts.fresh + counts.aging + counts.stale) / pages.length * 100);

  return (
    <div className={styles.dashboard}>
      <div className={styles.cards}>
        <button
          className={`${styles.card} ${statusFilter === 'all' ? styles.cardActive : ''}`}
          onClick={() => setStatusFilter('all')}>
          <span className={styles.cardNum}>{pages.length}</span>
          <span className={styles.cardLabel}>Total pages</span>
        </button>
        {(Object.keys(STATUS_META) as Status[]).map((s) => (
          <button
            key={s}
            className={`${styles.card} ${styles[s]} ${statusFilter === s ? styles.cardActive : ''}`}
            onClick={() => setStatusFilter(statusFilter === s ? 'all' : s)}>
            <span className={styles.cardNum}>
              <span className={styles.dot} aria-hidden="true" /> {counts[s]}
            </span>
            <span className={styles.cardLabel}>{STATUS_META[s].label}</span>
          </button>
        ))}
      </div>

      <p className={styles.meta}>
        <strong>{verifiedPct}%</strong> of pages carry a freshness stamp · last
        index rebuild <code>{data.generatedAt}</code>. A page is{' '}
        <em>Fresh</em> for {FRESH_DAYS} days after its last verification,{' '}
        <em>Aging</em> up to {AGING_DAYS}, then <em>Stale</em>.{' '}
        <span className={`${styles.dot} ${styles.unverified}`} aria-hidden="true" />{' '}
        Unverified pages
        have no <code>&lt;VerifyNote&gt;</code> yet — the perfect first contribution.
      </p>

      <div className={styles.controls}>
        <label>
          Section{' '}
          <select value={sectionFilter} onChange={(e) => setSectionFilter(e.target.value)}>
            {sections.map((s) => (
              <option key={s} value={s}>
                {s === 'all' ? 'All sections' : s}
              </option>
            ))}
          </select>
        </label>
        <label>
          Sort by{' '}
          <select value={sortBy} onChange={(e) => setSortBy(e.target.value as any)}>
            <option value="age">Needs attention first</option>
            <option value="title">Title (A–Z)</option>
            <option value="section">Section</option>
          </select>
        </label>
        <span className={styles.resultCount}>{rows.length} shown</span>
      </div>

      <div className={styles.tableWrap}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Page</th>
              <th>Section</th>
              <th>Last verified</th>
              <th>Status</th>
              <th aria-label="Actions" />
            </tr>
          </thead>
          <tbody>
            {rows.map((p) => (
              <tr key={p.url}>
                <td>
                  <Link to={p.url}>{p.title}</Link>
                </td>
                <td>
                  <code className={styles.section}>{p.section}</code>
                </td>
                <td>
                  {p.lastVerified ? (
                    <>
                      {p.lastVerified}{' '}
                      <span className={styles.ago}>
                        ({daysSince(p.lastVerified)}d ago)
                      </span>
                    </>
                  ) : (
                    <span className={styles.ago}>—</span>
                  )}
                </td>
                <td>
                  <span className={`${styles.badge} ${styles[p.status]}`}>
                    <span className={styles.dot} aria-hidden="true" />{' '}
                    {STATUS_META[p.status].label}
                  </span>
                </td>
                <td className={styles.actions}>
                  <a href={p.editUrl} target="_blank" rel="noreferrer">
                    {p.lastVerified ? 'Re-verify' : 'Verify'} ↗
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// Client-only: the dashboard computes freshness against the reader's live "today"
// (Date.now()), which differs from the build-time SSR render. Rendering it only in
// the browser avoids a React hydration mismatch (#418).
export default function FreshnessDashboard(): ReactNode {
  return <BrowserOnly>{() => <FreshnessDashboardInner />}</BrowserOnly>;
}
